# Generated by Django 3.0.5 on 2021-08-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210809_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default=0, help_text='Time for the quiz', max_length=1000),
        ),
    ]
