# Generated by Django 3.0.5 on 2021-08-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210813_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.PositiveIntegerField(help_text='time for quiz in minutes'),
        ),
    ]
