# Generated by Django 3.0.5 on 2021-08-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210813_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
    ]
