# Generated by Django 3.0.5 on 2021-08-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210824_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
